"""create_schema

Revision ID: d3fe3082cb04
Revises: 20251219_payroll_export
Create Date: 2025-12-23 13:09:49.148987

"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3fe3082cb04"
down_revision: str | None = "20251219_payroll_export"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs_archive",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "archived_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_type", sa.String(length=50), nullable=False),
        sa.Column("actor_ip", postgresql.INET(), nullable=True),
        sa.Column("actor_user_agent", sa.String(length=500), nullable=True),
        sa.Column(
            "action",
            sa.Enum(
                "CREATE",
                "UPDATE",
                "DELETE",
                "STATUS_CHANGE",
                "APPROVAL",
                "REJECTION",
                "DELEGATION",
                "ESCALATION",
                "ACCRUAL",
                "ADJUSTMENT",
                "ENCASHMENT",
                "CARRY_FORWARD",
                "EXPIRY",
                "LOGIN",
                "LOGOUT",
                name="auditaction",
            ),
            nullable=False,
        ),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("old_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("request_id", sa.String(length=100), nullable=True),
        sa.Column("session_id", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_logs_archive_id"), "audit_logs_archive", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_archive_timestamp"),
        "audit_logs_archive",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "organizations",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("fiscal_year_start_month", sa.String(length=2), nullable=True),
        sa.Column("timezone", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organizations_code"), "organizations", ["code"], unique=True
    )
    op.create_index(op.f("ix_organizations_id"), "organizations", ["id"], unique=False)
    op.create_table(
        "departments",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["departments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_departments_code"), "departments", ["code"], unique=False)
    op.create_index(op.f("ix_departments_id"), "departments", ["id"], unique=False)
    op.create_table(
        "holiday_calendars",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "code", "year", name="uq_holiday_calendar_org_code_year"
        ),
    )
    op.create_index(
        op.f("ix_holiday_calendars_code"), "holiday_calendars", ["code"], unique=False
    )
    op.create_index(
        op.f("ix_holiday_calendars_id"), "holiday_calendars", ["id"], unique=False
    )
    op.create_table(
        "leave_types",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("unit", sa.Enum("DAYS", "HOURS", name="leaveunit"), nullable=False),
        sa.Column("is_paid", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("color_code", sa.String(length=7), nullable=True),
        sa.Column("icon", sa.String(length=50), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=True),
        sa.Column("requires_document", sa.Boolean(), nullable=True),
        sa.Column("requires_reason", sa.Boolean(), nullable=True),
        sa.Column("min_days_per_request", sa.Float(), nullable=True),
        sa.Column("max_days_per_request", sa.Float(), nullable=True),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "code", name="uq_leave_type_org_code"),
    )
    op.create_index(op.f("ix_leave_types_code"), "leave_types", ["code"], unique=False)
    op.create_index(op.f("ix_leave_types_id"), "leave_types", ["id"], unique=False)
    op.create_table(
        "notification_templates",
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "notification_type",
            sa.Enum("EMAIL", "IN_APP", "SMS", "PUSH", name="notificationtype"),
            nullable=False,
        ),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("subject_template", sa.String(length=500), nullable=True),
        sa.Column("body_template", sa.Text(), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_templates_code"),
        "notification_templates",
        ["code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_templates_id"),
        "notification_templates",
        ["id"],
        unique=False,
    )
    op.create_table(
        "workflow_configurations",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("auto_approve_enabled", sa.Boolean(), nullable=True),
        sa.Column("auto_approve_max_days", sa.Float(), nullable=True),
        sa.Column("escalation_enabled", sa.Boolean(), nullable=True),
        sa.Column("escalation_hours", sa.Integer(), nullable=True),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_configurations_code"),
        "workflow_configurations",
        ["code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_configurations_id"),
        "workflow_configurations",
        ["id"],
        unique=False,
    )
    op.create_table(
        "holidays",
        sa.Column("calendar_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("is_optional", sa.Boolean(), nullable=True),
        sa.Column("is_half_day", sa.Boolean(), nullable=True),
        sa.Column("locations", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["calendar_id"],
            ["holiday_calendars.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("calendar_id", "date", name="uq_holiday_calendar_date"),
    )
    op.create_index(op.f("ix_holidays_date"), "holidays", ["date"], unique=False)
    op.create_index(op.f("ix_holidays_id"), "holidays", ["id"], unique=False)
    op.create_table(
        "leave_policies",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("leave_type_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "accrual_frequency",
            sa.Enum(
                "DAILY",
                "WEEKLY",
                "BI_WEEKLY",
                "MONTHLY",
                "QUARTERLY",
                "SEMI_ANNUALLY",
                "ANNUALLY",
                "ONE_TIME",
                name="accrualfrequency",
            ),
            nullable=False,
        ),
        sa.Column("accrual_amount", sa.Float(), nullable=False),
        sa.Column("accrual_cap", sa.Float(), nullable=True),
        sa.Column("prorate_on_join", sa.Boolean(), nullable=True),
        sa.Column("prorate_on_exit", sa.Boolean(), nullable=True),
        sa.Column(
            "carry_forward_type",
            sa.Enum(
                "NONE", "UNLIMITED", "CAPPED", "PERCENTAGE", name="carryforwardtype"
            ),
            nullable=True,
        ),
        sa.Column("carry_forward_limit", sa.Float(), nullable=True),
        sa.Column("carry_forward_expiry_months", sa.Integer(), nullable=True),
        sa.Column(
            "eligibility_type",
            sa.Enum(
                "IMMEDIATE",
                "AFTER_PROBATION",
                "AFTER_TENURE",
                "CUSTOM",
                name="eligibilitytype",
            ),
            nullable=True,
        ),
        sa.Column("eligibility_tenure_days", sa.Integer(), nullable=True),
        sa.Column(
            "eligibility_rules", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("encashment_allowed", sa.Boolean(), nullable=True),
        sa.Column("encashment_min_balance", sa.Float(), nullable=True),
        sa.Column("encashment_max_days", sa.Float(), nullable=True),
        sa.Column("lop_after_exhaustion", sa.Boolean(), nullable=True),
        sa.Column("allow_negative_balance", sa.Boolean(), nullable=True),
        sa.Column("negative_balance_limit", sa.Float(), nullable=True),
        sa.Column("include_weekends", sa.Boolean(), nullable=True),
        sa.Column("include_holidays", sa.Boolean(), nullable=True),
        sa.Column(
            "advanced_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("accrual_amount >= 0", name="ck_accrual_amount_positive"),
        sa.ForeignKeyConstraint(
            ["leave_type_id"],
            ["leave_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "code", name="uq_leave_policy_org_code"),
    )
    op.create_index(
        op.f("ix_leave_policies_code"), "leave_policies", ["code"], unique=False
    )
    op.create_index(
        op.f("ix_leave_policies_id"), "leave_policies", ["id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("employee_id", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("sso_provider", sa.String(length=50), nullable=True),
        sa.Column("sso_subject_id", sa.String(length=255), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=True),
        sa.Column("manager_id", sa.UUID(), nullable=True),
        sa.Column("job_title", sa.String(length=255), nullable=True),
        sa.Column("employment_type", sa.String(length=50), nullable=True),
        sa.Column("hire_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("probation_end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("termination_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "SUSPENDED", "TERMINATED", name="userstatus"),
            nullable=False,
        ),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_employee_id"), "users", ["employee_id"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "accrual_schedules",
        sa.Column("policy_id", sa.UUID(), nullable=False),
        sa.Column("scheduled_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("users_processed", sa.Integer(), nullable=True),
        sa.Column("total_accrued", sa.Float(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["leave_policies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_accrual_schedules_id"), "accrual_schedules", ["id"], unique=False
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_type", sa.String(length=50), nullable=False),
        sa.Column("actor_ip", postgresql.INET(), nullable=True),
        sa.Column("actor_user_agent", sa.String(length=500), nullable=True),
        sa.Column(
            "action",
            sa.Enum(
                "CREATE",
                "UPDATE",
                "DELETE",
                "STATUS_CHANGE",
                "APPROVAL",
                "REJECTION",
                "DELEGATION",
                "ESCALATION",
                "ACCRUAL",
                "ADJUSTMENT",
                "ENCASHMENT",
                "CARRY_FORWARD",
                "EXPIRY",
                "LOGIN",
                "LOGOUT",
                name="auditaction",
            ),
            nullable=False,
        ),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("old_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("request_id", sa.String(length=100), nullable=True),
        sa.Column("session_id", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_action_entity", "audit_logs", ["action", "entity_type"], unique=False
    )
    op.create_index(
        "ix_audit_actor_timestamp",
        "audit_logs",
        ["actor_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        "ix_audit_entity", "audit_logs", ["entity_type", "entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_entity_type"), "audit_logs", ["entity_type"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_id"), "audit_logs", ["id"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_timestamp"), "audit_logs", ["timestamp"], unique=False
    )
    op.create_index(
        "ix_audit_org_timestamp",
        "audit_logs",
        ["organization_id", "timestamp"],
        unique=False,
    )
    op.create_table(
        "leave_balances",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("leave_type_id", sa.UUID(), nullable=False),
        sa.Column("policy_id", sa.UUID(), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("opening_balance", sa.Float(), nullable=False),
        sa.Column("accrued", sa.Float(), nullable=False),
        sa.Column("used", sa.Float(), nullable=False),
        sa.Column("pending", sa.Float(), nullable=False),
        sa.Column("adjusted", sa.Float(), nullable=False),
        sa.Column("carried_forward", sa.Float(), nullable=False),
        sa.Column("encashed", sa.Float(), nullable=False),
        sa.Column("expired", sa.Float(), nullable=False),
        sa.Column("last_accrual_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_accrual_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["leave_type_id"],
            ["leave_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["leave_policies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "leave_type_id", "period_start", name="uq_user_leave_type_period"
        ),
    )
    op.create_index(
        "ix_balance_user_period",
        "leave_balances",
        ["user_id", "period_start", "period_end"],
        unique=False,
    )
    op.create_index(
        "ix_balance_user_type_period",
        "leave_balances",
        ["user_id", "leave_type_id", "period_start", "period_end"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_balances_id"), "leave_balances", ["id"], unique=False
    )
    op.create_table(
        "leave_requests",
        sa.Column("request_number", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("leave_type_id", sa.UUID(), nullable=False),
        sa.Column("policy_id", sa.UUID(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("total_days", sa.Float(), nullable=False),
        sa.Column("is_half_day_start", sa.Boolean(), nullable=True),
        sa.Column("is_half_day_end", sa.Boolean(), nullable=True),
        sa.Column("start_session", sa.String(length=20), nullable=True),
        sa.Column("end_session", sa.String(length=20), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("contact_during_leave", sa.String(length=255), nullable=True),
        sa.Column(
            "attachments", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PENDING_APPROVAL",
                "APPROVED",
                "REJECTED",
                "CANCELLED",
                "WITHDRAWN",
                name="leaverequeststatus",
            ),
            nullable=False,
        ),
        sa.Column("current_workflow_step", sa.Integer(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by", sa.UUID(), nullable=True),
        sa.Column("decision_remarks", sa.Text(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_by", sa.UUID(), nullable=True),
        sa.Column("cancellation_reason", sa.Text(), nullable=True),
        sa.Column("is_backdated", sa.Boolean(), nullable=True),
        sa.Column("is_lop", sa.Boolean(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["cancelled_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["leave_type_id"],
            ["leave_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["leave_policies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_leave_request_status_dates",
        "leave_requests",
        ["status", "start_date", "end_date"],
        unique=False,
    )
    op.create_index(
        "ix_leave_request_user_dates",
        "leave_requests",
        ["user_id", "start_date", "end_date"],
        unique=False,
    )
    op.create_index(
        "ix_leave_request_user_status",
        "leave_requests",
        ["user_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_requests_end_date"), "leave_requests", ["end_date"], unique=False
    )
    op.create_index(
        op.f("ix_leave_requests_id"), "leave_requests", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_leave_requests_request_number"),
        "leave_requests",
        ["request_number"],
        unique=True,
    )
    op.create_index(
        op.f("ix_leave_requests_start_date"),
        "leave_requests",
        ["start_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_requests_status"), "leave_requests", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_leave_requests_user_id"), "leave_requests", ["user_id"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("template_id", sa.UUID(), nullable=True),
        sa.Column(
            "notification_type",
            sa.Enum("EMAIL", "IN_APP", "SMS", "PUSH", name="notificationtype"),
            nullable=False,
        ),
        sa.Column("subject", sa.String(length=500), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recipient_address", sa.String(length=255), nullable=True),
        sa.Column("delivery_status", sa.String(length=50), nullable=True),
        sa.Column("delivery_error", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["notification_templates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notifications_id"), "notifications", ["id"], unique=False)
    op.create_index(
        op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False
    )
    op.create_table(
        "policy_assignments",
        sa.Column("policy_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("department_id", sa.UUID(), nullable=True),
        sa.Column("criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["leave_policies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_policy_assignments_id"), "policy_assignments", ["id"], unique=False
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "EMPLOYEE",
                "MANAGER",
                "HR_ADMIN",
                "SYSTEM_ADMIN",
                "AUDITOR",
                name="userrole",
            ),
            nullable=False,
        ),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=True,
        ),
        sa.Column("granted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["granted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "role"),
    )
    op.create_table(
        "workflow_step_configurations",
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("step_order", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("approver_type", sa.String(length=50), nullable=False),
        sa.Column("specific_approver_id", sa.UUID(), nullable=True),
        sa.Column("approver_role", sa.String(length=50), nullable=True),
        sa.Column(
            "skip_conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("allow_delegation", sa.Boolean(), nullable=True),
        sa.Column("escalation_hours", sa.Integer(), nullable=True),
        sa.Column("escalate_to_type", sa.String(length=50), nullable=True),
        sa.Column("escalate_to_id", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["escalate_to_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["specific_approver_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflow_configurations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_step_configurations_id"),
        "workflow_step_configurations",
        ["id"],
        unique=False,
    )
    op.create_table(
        "balance_transactions",
        sa.Column("balance_id", sa.UUID(), nullable=False),
        sa.Column("leave_request_id", sa.UUID(), nullable=True),
        sa.Column("transaction_type", sa.String(length=50), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("balance_after", sa.Float(), nullable=False),
        sa.Column("reference", sa.String(length=255), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("performed_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["balance_id"],
            ["leave_balances.id"],
        ),
        sa.ForeignKeyConstraint(
            ["leave_request_id"],
            ["leave_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["performed_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_balance_transactions_id"), "balance_transactions", ["id"], unique=False
    )
    op.create_table(
        "delegations",
        sa.Column("delegator_id", sa.UUID(), nullable=False),
        sa.Column("delegate_id", sa.UUID(), nullable=False),
        sa.Column(
            "delegation_type",
            sa.Enum(
                "TEMPORARY", "PERMANENT", "SPECIFIC_REQUEST", name="delegationtype"
            ),
            nullable=False,
        ),
        sa.Column("leave_request_id", sa.UUID(), nullable=True),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["delegate_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["delegator_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["leave_request_id"],
            ["leave_requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_delegations_id"), "delegations", ["id"], unique=False)
    op.create_table(
        "leave_request_comments",
        sa.Column("leave_request_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("is_internal", sa.Boolean(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["leave_request_id"],
            ["leave_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_leave_request_comments_id"),
        "leave_request_comments",
        ["id"],
        unique=False,
    )
    op.create_table(
        "leave_request_dates",
        sa.Column("leave_request_id", sa.UUID(), nullable=False),
        sa.Column("leave_date", sa.Date(), nullable=False),
        sa.Column("day_value", sa.Float(), nullable=True),
        sa.Column("is_holiday", sa.Boolean(), nullable=True),
        sa.Column("is_weekend", sa.Boolean(), nullable=True),
        sa.Column("holiday_name", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["leave_request_id"],
            ["leave_requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("leave_request_id", "leave_date", name="uq_request_date"),
    )
    op.create_index(
        op.f("ix_leave_request_dates_id"), "leave_request_dates", ["id"], unique=False
    )
    op.create_table(
        "workflow_steps",
        sa.Column("leave_request_id", sa.UUID(), nullable=False),
        sa.Column("step_config_id", sa.UUID(), nullable=True),
        sa.Column("step_order", sa.Integer(), nullable=False),
        sa.Column("step_name", sa.String(length=255), nullable=False),
        sa.Column("approver_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "SKIPPED",
                "ESCALATED",
                "DELEGATED",
                name="workflowstepstatus",
            ),
            nullable=False,
        ),
        sa.Column("actioned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("action_remarks", sa.Text(), nullable=True),
        sa.Column("delegated_from_id", sa.UUID(), nullable=True),
        sa.Column("delegated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("escalated_from_id", sa.UUID(), nullable=True),
        sa.Column("escalated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("escalation_reason", sa.Text(), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["approver_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["delegated_from_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["escalated_from_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["leave_request_id"],
            ["leave_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["step_config_id"],
            ["workflow_step_configurations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_steps_id"), "workflow_steps", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_payroll_export_records_id"),
        "payroll_export_records",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_payroll_export_records_id"), table_name="payroll_export_records"
    )
    op.drop_index(op.f("ix_workflow_steps_id"), table_name="workflow_steps")
    op.drop_table("workflow_steps")
    op.drop_index(op.f("ix_leave_request_dates_id"), table_name="leave_request_dates")
    op.drop_table("leave_request_dates")
    op.drop_index(
        op.f("ix_leave_request_comments_id"), table_name="leave_request_comments"
    )
    op.drop_table("leave_request_comments")
    op.drop_index(op.f("ix_delegations_id"), table_name="delegations")
    op.drop_table("delegations")
    op.drop_index(op.f("ix_balance_transactions_id"), table_name="balance_transactions")
    op.drop_table("balance_transactions")
    op.drop_index(
        op.f("ix_workflow_step_configurations_id"),
        table_name="workflow_step_configurations",
    )
    op.drop_table("workflow_step_configurations")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_policy_assignments_id"), table_name="policy_assignments")
    op.drop_table("policy_assignments")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_leave_requests_user_id"), table_name="leave_requests")
    op.drop_index(op.f("ix_leave_requests_status"), table_name="leave_requests")
    op.drop_index(op.f("ix_leave_requests_start_date"), table_name="leave_requests")
    op.drop_index(op.f("ix_leave_requests_request_number"), table_name="leave_requests")
    op.drop_index(op.f("ix_leave_requests_id"), table_name="leave_requests")
    op.drop_index(op.f("ix_leave_requests_end_date"), table_name="leave_requests")
    op.drop_index("ix_leave_request_user_status", table_name="leave_requests")
    op.drop_index("ix_leave_request_user_dates", table_name="leave_requests")
    op.drop_index("ix_leave_request_status_dates", table_name="leave_requests")
    op.drop_table("leave_requests")
    op.drop_index(op.f("ix_leave_balances_id"), table_name="leave_balances")
    op.drop_index("ix_balance_user_type_period", table_name="leave_balances")
    op.drop_index("ix_balance_user_period", table_name="leave_balances")
    op.drop_table("leave_balances")
    op.drop_index("ix_audit_org_timestamp", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_timestamp"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_index("ix_audit_entity", table_name="audit_logs")
    op.drop_index("ix_audit_actor_timestamp", table_name="audit_logs")
    op.drop_index("ix_audit_action_entity", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_accrual_schedules_id"), table_name="accrual_schedules")
    op.drop_table("accrual_schedules")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_employee_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_leave_policies_id"), table_name="leave_policies")
    op.drop_index(op.f("ix_leave_policies_code"), table_name="leave_policies")
    op.drop_table("leave_policies")
    op.drop_index(op.f("ix_holidays_id"), table_name="holidays")
    op.drop_index(op.f("ix_holidays_date"), table_name="holidays")
    op.drop_table("holidays")
    op.drop_index(
        op.f("ix_workflow_configurations_id"), table_name="workflow_configurations"
    )
    op.drop_index(
        op.f("ix_workflow_configurations_code"), table_name="workflow_configurations"
    )
    op.drop_table("workflow_configurations")
    op.drop_index(
        op.f("ix_notification_templates_id"), table_name="notification_templates"
    )
    op.drop_index(
        op.f("ix_notification_templates_code"), table_name="notification_templates"
    )
    op.drop_table("notification_templates")
    op.drop_index(op.f("ix_leave_types_id"), table_name="leave_types")
    op.drop_index(op.f("ix_leave_types_code"), table_name="leave_types")
    op.drop_table("leave_types")
    op.drop_index(op.f("ix_holiday_calendars_id"), table_name="holiday_calendars")
    op.drop_index(op.f("ix_holiday_calendars_code"), table_name="holiday_calendars")
    op.drop_table("holiday_calendars")
    op.drop_index(op.f("ix_departments_id"), table_name="departments")
    op.drop_index(op.f("ix_departments_code"), table_name="departments")
    op.drop_table("departments")
    op.drop_index(op.f("ix_organizations_id"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_code"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(
        op.f("ix_audit_logs_archive_timestamp"), table_name="audit_logs_archive"
    )
    op.drop_index(op.f("ix_audit_logs_archive_id"), table_name="audit_logs_archive")
    op.drop_table("audit_logs_archive")
    # ### end Alembic commands ###
