"""
Core module - database, config, enums, and exceptions.
"""
from .config import Settings, get_settings
from .database import Base, SessionLocal, engine, get_db
from .enums import (
    AccrualFrequency,
    AuditAction,
    CarryForwardType,
    DelegationType,
    EligibilityType,
    LeaveRequestStatus,
    LeaveUnit,
    NotificationType,
    UserRole,
    UserStatus,
    WorkflowStepStatus,
)
from .exceptions import (
    ApprovalException,
    AuthorizationException,
    DelegationException,
    DuplicateEntityException,
    EligibilityException,
    EncashmentException,
    EntityNotFoundException,
    EscalationException,
    InactiveUserException,
    InsufficientBalanceException,
    LeaveException,
    LeaveOverlapException,
    LeaveRequestNotFoundException,
    LeaveTypeNotFoundException,
    LMSException,
    PermissionDeniedException,
    PolicyException,
    PolicyNotFoundException,
    PolicyValidationException,
    RepositoryException,
    WorkflowException,
    WorkflowNotFoundException,
    WorkflowStateException,
)

__all__ = [
    # Database
    "Base",
    "engine",
    "SessionLocal",
    "get_db",
    # Config
    "Settings",
    "get_settings",
    # Enums
    "UserRole",
    "UserStatus",
    "LeaveRequestStatus",
    "WorkflowStepStatus",
    "AccrualFrequency",
    "LeaveUnit",
    "CarryForwardType",
    "EligibilityType",
    "AuditAction",
    "NotificationType",
    "DelegationType",
    # Exceptions
    "LMSException",
    "PolicyException",
    "PolicyNotFoundException",
    "PolicyValidationException",
    "InsufficientBalanceException",
    "EligibilityException",
    "WorkflowException",
    "WorkflowNotFoundException",
    "WorkflowStateException",
    "ApprovalException",
    "DelegationException",
    "EscalationException",
    "LeaveException",
    "LeaveRequestNotFoundException",
    "LeaveTypeNotFoundException",
    "LeaveOverlapException",
    "EncashmentException",
    "RepositoryException",
    "EntityNotFoundException",
    "DuplicateEntityException",
    "AuthorizationException",
    "PermissionDeniedException",
    "InactiveUserException",
]
